2021-11-08 12:21:25.982768: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64
2021-11-08 12:21:25.982810: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Input file is " ./agnet.specialmodel.8.checkpoint
Output file is " 
Image path is " ./databaserelease2/NatureDataset/test
--------------------


Traceback (most recent call last):
  File "./train.py", line 566, in <module>
    main(sys.argv[1:])
  File "./train.py", line 561, in main
    test(modelin,imagepath)
  File "./train.py", line 448, in test
    model = models.load_model(modelin)
  File "/mnt/beegfs/home/agolchub/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 211, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/mnt/beegfs/home/agolchub/miniconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 111, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: ./agnet.specialmodel.8.checkpoint/{saved_model.pbtxt|saved_model.pb}
srun: error: nodegpu003: task 0: Exited with exit code 1
