Input file is " ./segment_complete.train
Output file is " 
Image path is " ./databaserelease2/test.csv
--------------------


Traceback (most recent call last):
  File "/mnt/beegfs/home/agolchub/repo/Aesthetic_Photo_Ranking/./train_segmented.py", line 595, in <module>
    main(sys.argv[1:])
  File "/mnt/beegfs/home/agolchub/repo/Aesthetic_Photo_Ranking/./train_segmented.py", line 590, in main
    test(modelin,imagepath,WIDTH,HEIGHT,outColumn)
  File "/mnt/beegfs/home/agolchub/repo/Aesthetic_Photo_Ranking/./train_segmented.py", line 462, in test
    model = models.load_model(modelin)
  File "/mnt/beegfs/home/agolchub/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/mnt/beegfs/home/agolchub/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/keras/saving/saved_model/load.py", line 108, in load
    meta_graph_def = tf.__internal__.saved_model.parse_saved_model(path).meta_graphs[0]
  File "/mnt/beegfs/home/agolchub/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py", line 118, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: ./segment_complete.train/{saved_model.pbtxt|saved_model.pb}
srun: error: nodegpu002: task 0: Exited with exit code 1
